apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Workflow

on:
  push:
    branches:
      - '**'

jobs:
  build-and-publsh:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello jenkins"
      
      # use the run-jenkins-tko-job preconfigured action to run a job
      - name: Build image with Jenkins
        uses: run-jenkins-tko-job
        with:
          job-name: insurance-frontend

