apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Workflow

on:
  push:
    branches:
      - '**'

env:
  UNIQUE_PREFIX: sw
  APP_NAME: insurance-frontend
  HOSTNAME: insurance-frontend.arch.beescloud.com

jobs:
  build-container:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello jenkins"
      
      # use the run-jenkins-tko-job preconfigured action to run a job
      - name: Build image with Jenkins
        uses: run-jenkins-tko-job
        with:
          job-name: insurance-frontend

  build-helm:
    needs:
      - build-container
    steps:  
      - name: Checkout
        uses: cloudbees-io/checkout@v1    

      - name: Login to AWS
        uses: cloudbees-io/configure-aws-credentials@v1
        id: aws-login
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ vars.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          role-to-assume: cloudbees-infra-mgmt
          role-duration-seconds: "3600" # need to override default of 6h as our role has 1h max.

      - name: Configure container registry 
        uses: cloudbees-io/configure-ecr-credentials@v1

      - id: helmpkg
        name: Package Helm chart
        uses: cloudbees-io/helm-package@v1
        with:
          chart: ./chart
          destination: ./packaged-charts
          version: "0.0.1"
          values: |
            image:
              repository:  ${{ steps.aws-login.outputs.aws-account-id }}.dkr.ecr.us-east-1.amazonaws.com/${{ env.APP_NAME }}-image
              tag: 13

      - name: Publish Helm chart
        id: helm-publish
        uses: cloudbees-io/helm-push@v1
        with:
          chart: ${{ steps.helmpkg.outputs.chart }}
          remote: oci://${{ steps.aws-login.outputs.aws-account-id }}.dkr.ecr.us-east-1.amazonaws.com

    outputs:
      chart-location: ${{ steps.helm-publish.outputs.chart }}
      chart-version: ${{ steps.helm-publish.outputs.version }}

deploy:
    needs:
      - build-and-publsh

    steps:
      - uses: cloudbees-io/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ vars.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          role-to-assume: cloudbees-infra-mgmt
          role-duration-seconds: "3600" # need to override default of 6h as our role has 1h max

      - uses: cloudbees-io/configure-eks-credentials@v1
        with:
          name: cloudbees-quickstart-cluster

      - uses: cloudbees-io/configure-ecr-credentials@v1

      - id: install-chart
        name: Install helm chart
        uses: cloudbees-io/helm-install@v1
        with:
          chart-location: ${{ needs.build-and-publsh.outputs.chart-location }}
          version: ${{ needs.build-and-publsh.outputs.chart-version }}
          release-name: ${{ env.UNIQUE_PREFIX }}-${{ env.APP_NAME }}
          namespace: ${{ env.UNIQUE_PREFIX }}-${{ env.APP_NAME }}
          values: |
            ingress:
              annotations:
                external-dns.alpha.kubernetes.io/hostname: ${{ env.HOSTNAME }}
              hosts:
                - host: ${{ env.HOSTNAME }}
                  paths:
                    - path: /
                      pathType: Prefix

